spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 608066320994-prg6d1seqjl4k9okova24mracmooro6q.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: UmrV1eIDrXjQ43zMNEkF
            client-secret: k0wtxmHZAS
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: nickname, email, profile_image

          kakao:
            client-id: 7164d4e3362904dcbdb3419f28d6318c
            client-secret: gzVez1kJldGyF02v6zBggbpYFYgHPwSr
            client-authentication-method: post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email, profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id




jwt.secret: 'Qf32zRz87cGgQ6XEbzkRyrDfharymBhqYIhYGcPBclmwtp1wTpLrRUrUyiEjNiOLvDbiAnc85QHCDhZ9wzmxncbvalskdjfhg'

app:
  auth:
    refresh-token-expiry: 604800000
    token-expiry: 1800000
    token-secret: 926D96C90030DD58429D2751AC1BDBBC

  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000
      - http://localhost:8080
      - http://3.37.47.43:8080
      - http://ec2-3-37-47-43.ap-northeast-2.compute.amazonaws.com:8080

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600